### ISSUE TITLE
Avoid using already created hashes for passwords - User factory

### ISSUE THREAD

**Issue by matiaslauriti** [MorganGonzales/user-crud#1]
It is not a good practice to "copy paste" a created password hash like `$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi` because no one knows what that is, what you can do (if you want a fixed password) is to use `bcrypt()` helper.

So the bottom line of code should be something like:

```php
'password' => bcrypt('123456'), // password
```

Doing so, anyone can understand what the real password is.

---

I know Laravel has this written by default, so this is a Tip !!!

https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/database/factories/UserFactory.php#L34

**Comment by MorganGonzales** [comment]
Thanks, @matiaslauriti (apologies for the super delayed response).
I agree with your statements above.

**Comment by MorganGonzales** [comment]
Resolved in https://github.com/MorganGonzales/user-crud/commit/2535328c21f65b159f57b6b5374cddbda39c2b6d
