### ISSUE TITLE
Do not use/append things you are not using - Models

### ISSUE THREAD

**Issue by matiaslauriti** [MorganGonzales/user-crud#2]
I was trying to run a package that will help me type hint a lot of things in the code ([barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper)) and it gave me an error on this model.

I investigated a little bit and I saw you are using the `HasFactory` trait but you do not have a `Factory` created for it. I can also see you are "using" this model in only one test file but you are not using it, only requiring it.

https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/app/Models/Detail.php#L10

https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/tests/Unit/Services/UserServiceTest.php#L5

https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/tests/Unit/Services/UserServiceTest.php#L13

That is bad as if you are not using a good IDE, you will see the `use` but you are really not using that class in your code and can confuse people !

**Comment by MorganGonzales** [comment]
Acknowledging this @matiaslauriti. Thanks for taking the effort of checking this stuff. I'm actually using PHPStorm, and I was planning to use the `App\Models\Detail` to have a factory but realizing it was not necessary for testing.

This issue is worth resolving 👍

**Comment by MorganGonzales** [comment]
Resolved in https://github.com/MorganGonzales/user-crud/commit/f9eea795c581fe98d0cb2148b441edd0e3b421b8
