### ISSUE TITLE
General things about User model

### ISSUE THREAD

**Issue by matiaslauriti** [MorganGonzales/user-crud#3]
First of all, I am going to "be picky" and this is my personal opinion after working with Laravel and some teams for at least 5 years, so this is not personal, just some tips and things to maybe fix.

### Again, do not leave `use` that are not being actually used
https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/app/Models/User.php#L6

---

#### Super personal opinion, order alphabetically here

https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/app/Models/User.php#L17-L33

It is really good to have all this array strings sorted alphabetically, so it is way easier to find whatever you want in that array, even if you have 2 or more elements. I recommend 100% to have any element sorted for `$fillable`, `$hidden`, `$casts` and any other "definition".

But do not sort in the migration, as you can have a visual order on the table (when looking at the columns, maybe you want first to have any relation id columns and then any hash and finally dates, that is okay to not have it sorted).

---

### Prefer class constants than private/protected static properties

If you want to have sort of an enum property in your object class (it doesn't matter if it is a Model, a Service, or whatever), prefer to use Class constants, so avoid doing:

https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/app/Models/User.php#L58-L62

And prefer doing:

```php
public const GENDER_PREFIX_MAP = [
    'Mr.' => 'Male',
    'Mrs.' => 'Female',
    'Ms.' => 'Female',
];
```

Doing so, you can use the indexes in your `UserFactory` (for example) instead of hardcoding them in there. So, that factory goes from:

https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/database/factories/UserFactory.php#L26

To:

```php
'prefixname' => collect(User::GENDER_PREFIX_MAP)->keys()->random(),
```

This way you avoid having to update that array (in the factory file) every time you add or remove a key/value. Also, you use `collection`s (Laravel way).

---

### Avoid creating attributes/methods you do not use

I did a find and search for `->avatar` and found nothing, so this is not used ! If you edit code that leaves other code not used anymore, please remove it as it will be confusing to know if that method is being used or not.

https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/app/Models/User.php#L69-L72

---

### Do almost everything the Laravel way if possible

I see this code:

https://github.com/MorganGonzales/user-crud/blob/5bbe15b0f92175752a95775b0fb8b6d7611a4a8f/app/Models/User.php#L74-L84

The "confusing" part is that mostly all PHP developers do not know what [array_filter()](https://www.php.net/manual/en/function.array-filter) do, most of them never saw/used that function, but Laravel uses it and it is built in the `Collection` itself ([filter](https://laravel.com/docs/8.x/collections#method-filter) method), and all Laravel developers know that, so it is more readable for everyone !

So it should look like this:

```php
public function getFullnameAttribute(): string
{
    $data = [
        $this->firstname,
        $this->middleinitial,
        $this->lastname,
        $this->suffixname,
    ];

    return collect($data)->filter()->join(' ');
}
```

If you want, you can also do:

```php
public function getFullnameAttribute(): string
{
    return collect([
        $this->firstname,
        $this->middleinitial,
        $this->lastname,
        $this->suffixname,
    ])->filter()->join(' ');
}
```

Or

```php
public function getFullnameAttribute(): string
{
    return collect([
        $this->firstname,
        $this->middleinitial,
        $this->lastname,
        $this->suffixname,
    ])
        ->filter()
        ->join(' ');
}
```

**Comment by MorganGonzales** [comment]
Now, some interesting comments you have here @matiaslauriti. And I believe this is where we differ a bit.
Again thanks for watching my back on those `use` cases not being used 👍 

First is the `alphabetical ordering` of the $fillable array: I used to order this based on the actual table structure and this array rarely gets modified (in my experience at least - you have more experience than me anyway 😃 ). 
But I guess doing it `alphabetical` is also a good option and can be simply be made as a standard (regardless of other devs being aware of the table structure or not). So good point on this, probably something I might also adapt 👍 

The second is doing the "Laravel way if possible". I really don't know how to react to the statement "mostly all PHP developers do not know what array_filter() do". To be honest, I would like to disagree on this here (and keep it as is). But I would rather take this opportunity to personally know the "Laravel way" as well 😄 

Really appreciate your comments being so detailed, and I like how you give examples on each. 
I wish I have teammates who are like you 😃. These are very constructive which I really like 👍

**Comment by matiaslauriti** [comment]
> Now, some interesting comments you have here @matiaslauriti. And I believe this is where we differ a bit.
> Again thanks for watching my back on those `use` cases not being used 👍
> 
> First is the `alphabetical ordering` of the $fillable array: I used to order this based on the actual table structure and this array rarely gets modified (in my experience at least - you have more experience than me anyway 😃 ).
> But I guess doing it `alphabetical` is also a good option and can be simply be made as a standard (regardless of other devs being aware of the table structure or not). So good point on this, probably something I might also adapt 👍
> 
> The second is doing the "Laravel way if possible". I really don't know how to react to the statement "mostly all PHP developers do not know what array_filter() do". To be honest, I would like to disagree on this here (and keep it as is). But I would rather take this opportunity to personally know the "Laravel way" as well 😄
> 
> Really appreciate your comments being so detailed, and I like how you give examples on each.
> I wish I have teammates who are like you 😃. These are very constructive which I really like 👍

Awesome !!!

About the alphabetical order: I know we sometimes like to see the same order in the attributes, but if you are new to the project or you are jumping from project to project, you are going to get crazier trying to search a field (that is not alphabetically ordered), just that.

About the `array_filter`, believe me there are a lot of developers (me included before using Laravel) that did not know `array_something` existed and was so useful... If you see a lot of pages like `StackOverflow` and `Laracasts` forums, you will see developers have no idea those functions exists.

**Comment by MorganGonzales** [comment]
Resolved in https://github.com/MorganGonzales/user-crud/commit/bbe31461346da44b281ceeaf85ecdeb93ad1a59d
